# -*- coding: utf-8 -*-
"""Loading Data

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yB3gDroqQJItMLcWUeNsm2R9UeF72YcG

Part 1: Using wget
"""

!wget https://archive.ics.uci.edu/ml/machine-learning-databases/arrhythmia/arrhythmia.data

!ls

!head arrhythmia.data

import pandas as pd
df = pd.read_csv('arrhythmia.data', header=None)

data = df[[0,1,2,3,4,5]]
data.colums = ['age', 'sex', 'height', 'weight', 'QRS duration', 'P-R interval']

import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [15,15]
data.hist();

from pandas.plotting import scatter_matrix
scatter_matrix(data);

"""Part 2: Using tf.keras"""

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'

!pip install -q tensorflow==2.1.0
import tensorflow as tf
print(tf.__version__)

tf.keras.utils.get_file('auto-mpg.data', url)

!head /root/.keras/datasets/auto-mpg.data

df = pd.read_csv('/root/.keras/datasets/auto-mpg.data', header=None, delim_whitespace=True)
df.head()

"""Part 3:uploading file yourself"""

from google.colab import files
uploaded = files.upload()

uploaded

!ls

"""Part 4: From Drive"""

from google.colab import drive
drive.mount('/content/gdrive')

!ls

!ls gdrive

